### ISSUE TITLE
View Progress Yes/No

### ISSUE THREAD

**Issue by peter-desrosiers** [peter-desrosiers/Potluck#2]
Self/Team

**Comment by brandoncornel** [comment]
![Simulator Screen Shot - iPhone 6 - 2018-03-05 at 12.26.44.png](https://zube.io/files/intuit-senior-project/4ea2f28016a0a0daef8e9b9843ddb388-simulator-screen-shot-iphone-6-2018-03-05-at-12-26-44.png)
