### ISSUE TITLE
View Progress Percent

### ISSUE THREAD

**Issue by peter-desrosiers** [peter-desrosiers/Potluck#3]
Self/Team

**Comment by brandoncornel** [comment]
![Simulator Screen Shot - iPhone 6 - 2018-03-06 at 15.24.01.png](https://zube.io/files/intuit-senior-project/bc14dbcb291457745fd4bb7cdd4d3c46-simulator-screen-shot-iphone-6-2018-03-06-at-15-24-01.png)
